### ISSUE TITLE
Compilation error if build with 10.11 SDK: cannot initialize a variable of type 'const CGEventField' with an rvalue of type 'int'

### ISSUE THREAD

**Issue by maxim-cliqz** [cliqz-oss/browser-f#99]
https://bugzilla.mozilla.org/show_bug.cgi?id=1187613
